# Generated by Django 6.0.3 on 2026-04-14 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='logs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.JSONField()),
                ('root_causes', models.JSONField()),
                ('suggested_fixes', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20)),
                ('error_count', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('raw_ai_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logs.logfile')),
            ],
        ),
        migrations.CreateModel(
            name='ParsedLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(max_length=20)),
                ('category', models.CharField(default='GENERAL', max_length=50)),
                ('message', models.TextField()),
                ('log_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.logfile')),
            ],
        ),
    ]
