# Generated by Django 6.0.3 on 2026-04-21 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('UPLOADING', 'Uploading'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADING', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.JSONField()),
                ('root_causes', models.JSONField()),
                ('suggested_fixes', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20)),
                ('error_count', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('raw_ai_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logs.logfile')),
            ],
        ),
        migrations.CreateModel(
            name='ParsedLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hash', models.CharField(db_index=True, max_length=64)),
                ('log_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.logfile')),
            ],
            options={
                'indexes': [models.Index(fields=['level'], name='logs_parsed_level_565266_idx'), models.Index(fields=['category'], name='logs_parsed_categor_f54e95_idx'), models.Index(fields=['log_file'], name='logs_parsed_log_fil_5b8f37_idx'), models.Index(fields=['hash'], name='logs_parsed_hash_545748_idx')],
                'unique_together': {('log_file', 'hash')},
            },
        ),
    ]
