# Generated by Django 6.0.3 on 2026-04-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfile',
            name='processed_lines',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logfile',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logfile',
            name='total_lines',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='logfile',
            name='status',
            field=models.CharField(default='PROCESSING', max_length=20),
        ),
    ]
